model:
  base_learning_rate: 5.0e-03
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    image_size: 64
    channels: 4
    cond_stage_trainable: true   # Note: different from the one we trained before
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    embedding_reg_weight: 0.0
    unfreeze_model: False
    model_lr: 0.0

    personalization_config:
      target: ldm.modules.embedding_manager.EmbeddingManagerId
      params:
        placeholder_strings: ['sks', 'ks', 'ata', 'tre', 'ry', 'bop', 'rn', '&', '*', '`']
        initializer_words: ["face", "face", "face", "face", "face", "face", "face", "face", "face", "face"]
        max_ids: 10  # joint learning #ids, consistent with data.train.num_ids
        num_embeds_per_token: 2  # consistent with cond_stage_config
        meta_mlp_depth: 1
        loss_type: 'none'
        meta_inner_dim: 512  # consistent with n_components
        meta_heads: 1
        use_rm_mlp: False
        test_mode: 'coefficient'  # coefficient/embedding/image/all
        momentum: 0.9
        save_fp16: False

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 512
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder
      params:
        use_celeb: True
        use_svd: True
        rm_repeats: True
        celeb_txt: "./infer_images/wiki_names_v2.txt"  # celebs, wiki_names_v1
        n_components: 512  # consistent with meta_inner_dim, should be <= n_samples-1
        use_sample_reduce: False
        n_samples: 513
        use_flatten: False
        num_embeds_per_token: 2  # consistent with personalization_config

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 4
    wrap: false
    train:
      target: ldm.data.face_id.FaceIdDatasetOneShot
      params:
        pickle_path: "/content/datasets/stylegan/ffhq.pickle"  # /Your/Path/To/Images/ffhq.pickle
        split: train
        num_ids: 2
        specific_ids: [1,2]
        images_per_id: 1
        repeats: 1000
        reg_ids: 1000
        reg_repeats: 0
        diff_cnt: 0
    validation:
      target: ldm.data.face_id.FaceIdDatasetOneShot
      params:
        pickle_path: "/content/datasets/stylegan/ffhq.pickle"  # /Your/Path/To/Images/ffhq.pickle
        split: val
        num_ids: 1
        images_per_id: 1
        repeats: 1
        reg_repeats: 0
        diff_cnt: 0

lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 400
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1200
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
    max_steps: 1600